### ISSUE TITLE
Microphone access error

### ISSUE THREAD

**Issue by djfil** [SEPIA-Framework/sepia-html-client-app#23]
Wake word is recognised, but after the bip it returns a text message stating an access error to the microphone: "Microphone has not been recognized properly or access was denied."
I do have the permissions for microphone, location and storage set for the SEPIA android client. This was tested in 2 different Android devices.
And the same for the webclient... but here different message and at different stage:
"Porcupine error: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission."
Showing up at the test tool. Using safari.
With Chrome in the wake word test tool i get: "Porcupine error: Cannot create an audio stream recorder!" But it starts after a while, despite not responding (the test fails).
And the same as before when you try to push the wake word button: "Microphone has not been recognized properly or access was denied."

**Comment by fquirin** [comment]
Hello,

Please post your future questions here: https://github.com/SEPIA-Framework/sepia-docs/issues
It is the central place for all framework related issues and I might miss questions in other repos sometimes :see_no_evil: 

Are you saying it works in 2 Android clients, but currently fails in a 3rd one AND in the browser version?
When you say "Chrome" and "Safari" is this on iOS or MacOS? I'm asking because Chrome on iOS is not actually a "real" Chrome and I think I remember issues with Safari and audio streams.

**Comment by djfil** [comment]
Hi,

Sorry for the wrong posting, but I felt like this is a bug on the web interface.
Probably with the underlying porcupine lib...
But feel free to relocated this at your will.

Here are some more details:
- I installed from the Docker image.
- Then I updated to the latest version of SEPIA.
- Installed stt

When I say safari and chrome, I mean OSX 10.11.6
When I say android i mean a mobile phone running Android 7 and a Nexus 7 tablet running Android 6.0.1

**Comment by fquirin** [comment]
:thinking: 
Some users had troubles getting the Docker image working properly, but this should be unrelated because microphone permission is solely a client issue.  
The STT container is unrelated to wake-word as well so this should also be no problem.

> "Porcupine error: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission."

I can reproduce this error in Chrome and Firefox when I reject microphone access deliberately. Does everything work properly when you deactivate "Hey SEPIA"?

> Wake word is recognised, but after the bip it returns a text message stating an access error to the microphone: "Microphone has not been recognized properly or access was denied."

Does this happen with both "native" and "custom" setting for "ASR engine"?

**Comment by djfil** [comment]
> 🤔
> Some users had troubles getting the Docker image working properly, but this should be unrelated because microphone permission is solely a client issue.
> The STT container is unrelated to wake-word as well so this should also be no problem.
> 
Yes, I had problems too, but I overcame them...
> 
> I can reproduce this error in Chrome and Firefox when I reject microphone access deliberately. Does everything work properly when you deactivate "Hey SEPIA"?
> 
yes, the text msg interface seems fine.
> 
> Does this happen with both "native" and "custom" setting for "ASR engine"?
>
No, in fact with native on the phone and the tablet works fine. Although on Safari there is no native option and on chrome, native gives the same "Mic not recogn..." error as before and then a popup window with:
"porcupine error: Cannot create an audio stream recorder!"

**Comment by fquirin** [comment]
Thanks for the info, I'll build a new Docker image and probably do some tests on MacOS tomorrow to see if I can reproduce the issues.

**Comment by fquirin** [comment]
Something I just noticed for Firefox which might also be valid for other browsers: If the page ist not loaded from a secure origin (HTTPS or localhost/127.0.0.1) the browser will not even ask for microphone access anymore :angry: 
Do you have a chance to load the client from localhost or do you have a reverse proxy with SSL? For testing you could also use [ngrok](https://ngrok.com/) to generate a temporary HTTPS URL for your local address.

**Comment by fquirin** [comment]
There is some more info about it in the docs now and better error messages in the client:
https://github.com/SEPIA-Framework/sepia-docs/wiki/SSL-for-your-Server#troubles-with-microphone-or-server-access
